use aesccontracts;
DROP TABLE IF EXISTS `xmc_parkingspace`;
 SET character_set_client = utf8mb4 ;
CREATE TABLE `xmc_parkingspace` (
  `contract_id` int(11) NOT NULL AUTO_INCREMENT COMMENT '合同主键',
  `contract_serial` varchar(50) NOT NULL COMMENT '合同编号',
  `contract_title2` varchar(50) NOT NULL COMMENT '车位标题',
  `merchant_name` varchar(50) DEFAULT NULL COMMENT '承租方名称',
  `contract_title3` varchar(50) NOT NULL COMMENT '协议车位位置',
  `offer` varchar(500) NOT NULL COMMENT '停车位位置',
  `purpose` varchar(50) NOT NULL COMMENT '用途',
  `plate` varchar(20) NOT NULL COMMENT '车牌号',
  `contract_title4` varchar(50) NOT NULL COMMENT '车位位置',
  `year_start` varchar(20) NOT NULL COMMENT '年起',
  `month_start` varchar(20) NOT NULL COMMENT '月起',
  `day_start` varchar(20) NOT NULL COMMENT '日起',
  `year_end` varchar(20) NOT NULL COMMENT '年止',
  `month_end` varchar(20) NOT NULL COMMENT '月止',
  `day_end` varchar(20) NOT NULL COMMENT '日止',
  `service_charge` varchar(20) NOT NULL COMMENT '服务费',
  `total` varchar(20) NOT NULL COMMENT '共计',
  `numeral_sed` varchar(20) NOT NULL COMMENT '大写',
  `year_rd` varchar(20) NOT NULL COMMENT '年',
  `month_rd` varchar(20) NOT NULL COMMENT '月',
  `day_rd` varchar(20) NOT NULL COMMENT '日',
  `payment_way` varchar(20) NOT NULL COMMENT '支付方式',
  `payment_time` varchar(20) NOT NULL COMMENT '交款时间',
  `cash_deposit` varchar(20) NOT NULL COMMENT '保证金',
  `numeral_five` varchar(20) NOT NULL COMMENT '大写',
  `remark` varchar(1000) DEFAULT NULL COMMENT '备注',
  `first_agent` varchar(20) DEFAULT NULL COMMENT '甲方委托代理人',
  `first_date` date DEFAULT NULL COMMENT '甲方落款日期',
  `second_sign` varchar(20) DEFAULT NULL COMMENT '乙方签章',
  `second_agent` varchar(20) DEFAULT NULL COMMENT '乙方委托代理人',
  `second_phone` varchar(20) DEFAULT NULL COMMENT '乙方联系方式',
  `second_date` date DEFAULT NULL COMMENT '乙方落款时间',
  `username` varchar(10) NOT NULL COMMENT '录入人',
  `status` int(11) NOT NULL DEFAULT '1' COMMENT '有效状态',
  PRIMARY KEY (`contract_id`),
  UNIQUE KEY `contract_serial` (`contract_serial`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 COMMENT='新名车广场停车位合同表';